### ISSUE TITLE
Publish plugin migration guide

### ISSUE THREAD

**Issue by kdeldycke** [getpelican/pelican-blog#13]
There is a plugin migration tutorial available at: https://blog.getpelican.com/drafts/namespace-plugin-migration.html

The source of this document has not been published yet. Is this [tutorial still under embargo](https://github.com/getpelican/pelican-plugins/issues/425#issuecomment-701329181)?

For the context, this was asked by @cav71, who is working on the migration of the [`show-source` plugin](https://github.com/pelican-plugins/show-source). I guess he's looking to contribute some fixes about the migration path... 🙂

**Comment by justinmayer** [comment]
Please accept my sincere apologies for the delay in moving the guide from *draft* to being actually published. I will put the source to this repository soon, but at least the guide itself is no longer a draft and is now live: https://blog.getpelican.com/namespace-plugin-migration.html

**Comment by kdeldycke** [comment]
No worries! This ticket was just a simple friendly reminder to not forget about it, and meant to be picked up at a later date, whenever time or capacity allows. Thanks again @justinmayer for the quick fix! 😃
