### ISSUE TITLE
Move this off a server to Firebase / Netlify

### ISSUE THREAD

**Issue by rehanhaider** [getpelican/pelican-blog#14]
I just think it might save a cup of coffee or two at the same time improving page load times and showcase the "art of the possible".

PS: I'd be glad to help.

**Comment by justinmayer** [comment]
The site loads quickly for me. PageSpeed Insights currently shows a score of 98 out of 100, so it's clear that the site is loading *very* fast.

I don't understand the motivation behind filing this issue. What is the problem exactly?

**Comment by rehanhaider** [comment]
> I don't understand the motivation behind filing this issue. What is the problem exactly?

It's more of a suggestion than an issue. Pelican is the premier Python written "JAMStack" tool and its blog isn't following that architecture.  

> PageSpeed Insights currently shows a score of 98 out of 100

Not true, 88 / 90 - Mobile & Desktop respectively. Don't believe the Chrome/Edge Lighthouse tests, they are usually off by a bit. But that is beside the point.
